### ISSUE TITLE
Incorrect ordering of notes in reminders

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#112]
In Beta 5, I have some old reminders, and I made a new note with a reminder, and all the new notes go after the previous list of reminders, but one thing to note that the order among the new reminders is correct, meaning if I add two new notes with reminders then they show at the bottom of the old list but in the right order.

steps:
1. you need to have reminders with old ON
2. add new note with reminder
3. it shows after the old notes

one thing I observed,

![screenshot_2015-01-22-08-42-37](https://cloud.githubusercontent.com/assets/6261877/5849971/0c3219bc-a213-11e4-86f5-05452979d27e.png)

There is no year in the timestamp.

**Comment by federicoiosue** [comment]
Hi Suraj,

what do you mean with "old ON"? An old version of Omni Notes or a note with a past reminder?
I tried to reproduce but the resut I had seems to be correct as you can see.

![selezione_062](https://cloud.githubusercontent.com/assets/487104/5893624/bc75c85c-a4eb-11e4-819b-853d126e4136.png)

**Comment by thewhitetulip** [comment]
Old means set in a past version of ON and a reminder which has expired

**Comment by federicoiosue** [comment]
I can't reproduce the problem.

Could you please try to share a partial backup with a couple of notes affected by the issue?

You can achieve this by doing the following: do a full backup, remove **all** the other notes excepted some not privacy sensible examples, do a new backup and share that to me.

**Comment by thewhitetulip** [comment]
Hi I created the backup as you asked me to, I have compressed it, https://drive.google.com/file/d/0BzgU3VebHf3NUENGYlhGQzdHNXc/view?usp=sharing

the uncompressed folder should be the custom backup as you requested, and even in the latest beta the issue persists

**Comment by federicoiosue** [comment]
Here the result of the import of your file.

![device-2015-01-30-225020](https://cloud.githubusercontent.com/assets/487104/5984028/a250a2fe-a8d2-11e4-9115-b1e865c86ae9.png)

For what I can see everything is fine: notes are correclty ordered starting from the oldest to the newer. 
The last two notes don't show the year because the reminder are set for the current year, and this is a desired behavior.

Filtering out the old reminders I get

![device-2015-01-30-225313](https://cloud.githubusercontent.com/assets/487104/5984091/16cb5174-a8d3-11e4-887c-cd132dcae25d.png)

that once again seems to be correct.

Maybe the export/import process fixed your problem!

**Comment by thewhitetulip** [comment]
Oh, I hadn't realized that the way you wanted to order the reminders was old to new, I always thought it would be ordered from the latest to the oldest, because when I as a user will go to reminders I would expect the latest one to pop up on the top, what do you think about this?

**Comment by federicoiosue** [comment]
Until the previous released stable notes were effectively sorted from newer to oldest. 

Since the new version 5 I'd like to have a behavior more similar to an agenda, where you have your future reminders showed in the order they will be notified  with the option to look to the past is by disabling the filter.

**Comment by thewhitetulip** [comment]
I don't understand why one would like an agenda to be sorted from old to new, in case of people who use the app frequently, they will have a *lot* of reminders and sometimes those reminders will be old, means a year old or so, in these cases the app's functionality breaks because you have to scroll all the way down to see the latest reminders, the best practice I feel is to sort them newest to oldest because when done this way, it'll give more value to the user.

suppose I have four TODOs and three random reminders I set a year back, and I check ON for what tasks i have left in TODO, then I will need to scroll all the way past the old ones to find my TODO list when that could have accomplished without any additional scrolling had the sorting been newest to oldest

**Comment by federicoiosue** [comment]
As you could have noticed the behavior as been changed as follows:
1. Notes are sorted from the oldest to the newest
2. An option is available to hide passed reminders
3. The list will be automatically scrolled to the neares future event

This should work well for all the cases.

**Comment by thewhitetulip** [comment]
:like:
