### ISSUE TITLE
Software button overlap problem

### ISSUE THREAD

**Issue by musko** [federicoiosue/Omni-Notes#135]
Please fix the problem showing in screenshot, where software button overlay creation date and update time.

Thank you.

![screenshot_2015-04-03-09-29-43](https://cloud.githubusercontent.com/assets/7783470/6979482/8aeb099a-d9e4-11e4-80b8-b61b36bdb226.png)

Phone: Nexus 5, Android 5.1

**Comment by federicoiosue** [comment]
Yes @musko it's a known behavior.

On KitKat this is useful because the height where to put both the dates is calculated dynamically looking at the navigation bar.
Due to the fact that it was translucent the result was nice and it optimizes the available screen space.

On Lollipop we've got a full color and no more a gradient so the result is the one you're reporting.

Have you got any hint about how to manage it?

**Comment by musko** [comment]
Hellou **federicoiosue**, maybe only move slightly higher.

**Comment by federicoiosue** [comment]
Actually I decided to move them a little lower instead, calculating dynamically the navigation bar height in case someone is using a custom height (Xposed, custom ROM...).
