### ISSUE TITLE
OTA updates

### ISSUE THREAD

**Issue by thewhitetulip** [federicoiosue/Omni-Notes#151]
Earlier I used to get a notification that "There is a new update". I haven't seen them in quite a while.
I don't have google play settings on my phone, it would be nice if ON updated like whatsapp does

**Comment by Micks29** [comment]
Same here, I've received this "There is a new update" notification but each time there is no update available on Google Play, a bit buggy or it's an issue with beta channel.
Anyway I second the "OTA updates" request, it would be useful to have this but without add an option in settings would be even better for no "bloat" this great app.

**Comment by thewhitetulip** [comment]
Actually my intention was to show OTA updates irrespective of the play store, because some people including me don't use the Google play services on their phones, the OTA updates would be good for those users

**Comment by federicoiosue** [comment]
Currently an OTA feature is already active (it's based on a little PHP/JS service listed between the libraries used by ON in the Info screen) only for the stable channel.

The fact that on the beta channel you got the update dialog is an unwanted behavior that once happened due to a clone app that has been used (I don't know why)instead of mine to check the version. 

I'll check if this happened again.

**Comment by federicoiosue** [comment]
It seems everything is ok right now.

**Comment by thewhitetulip** [comment]
I am running on beta 14, I haven't got an update notification yet about the 16'th one that you published on g+

**Comment by federicoiosue** [comment]
And that's correct. Beta channel don't have an OTA update notification

**Comment by thewhitetulip** [comment]
Okay.
