### ISSUE TITLE
Daily Reminders not working

### ISSUE THREAD

**Issue by Tsunamii** [federicoiosue/Omni-Notes#153]
set a daily reminder (20:00) for two of my notes but it somehow only showed up once (the first day)

some infos:
sony xperia z2
android 5 (stamina mode but allowed notifications for omni notes)
(had 4.4 before but the same problem there
omni notes 5.0.0 beta 20

if you need more infos just let me know
or if you want me to test something

**Comment by federicoiosue** [comment]
Some complications may occur when a new reminder have to be set once the first of the serie has been fired due to:
- Device turning off/on
- Action performed when the notification is shown (postpone, snooze, dismiss, note opening...)
- Further modifications to the notes

I've refactored some code and added many unit tests to check the behavior and it seems to work correctly. I'll release it soon.

**Comment by federicoiosue** [comment]
@Tsunamii please after double checked that the new version 5.0.0 Beta 24 works well please close the issue.

Thanks!

**Comment by Tsunamii** [comment]
Tested it for 2 days. Seems to work flawless now :) big thanks :)
