### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by craig-s** [federicoiosue/Omni-Notes#166]
After the latest update, the app seems to take a lot longer to load the initial note list. This is not consistent though. One time it took 23 seconds. Another just 6.

**Comment by Micks29** [comment]
Same here, a bit weird because currently I have only one note created

**Comment by federicoiosue** [comment]
What about if you try to make a new backup from lastet app version, clean data and restore that again?

That's because whenever I do some changes to DB many tasks are started (on the next app fresh launch) to to necessary changes to existing notes.

This don't explain why the issue happens to @Micks29 that have just a note though, but it's an easy to do test.

**Comment by craig-s** [comment]
It SEEMS to have sorted the problem out for me. But it WAS random, so I will keep my eyes on things. Thanks. 
Oh, and (other that these small problems) a great release. :-)

**Comment by craig-s** [comment]
Just had a 30 second wait for the list view on startup, so I'm guessing that there is a problem here somewhere.

**Comment by federicoiosue** [comment]
Did you noticed if this appens also if you don't ever close the application?
I mean, just by pressing "home" to leave it instead of pressing "back".

**Comment by craig-s** [comment]
It only APPEARS  to happen when the app is closed. I will let you know otherwise if I experience anything different.

**Comment by Micks29** [comment]
I've noticed that loading take more time via using mobile data, why?
Btw I've already delete data then app and reinstal it but still randomly buggy.
