### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by jaimejimbo** [federicoiosue/Omni-Notes#175]
Password protection not working when app runing in background. If I press home button and then press home button for a while and select omni notes app, I get into the app without password input. I think it would be better to ask always for password.

**Comment by jaimejimbo** [comment]
BTW it happens only when I'm editing a note.

**Comment by federicoiosue** [comment]
Hi, actually the password system should help the user to protect his/her notes but obviously cannot replace some attention.

An auto-lock mechanism (as you have on a desktop) should be useless due to the fact that:
1. The device itself has an auto-lock protection
2. App switching is a so much frequent operation that asking for the password all the times you that you enter again on the same opened note would result in a loss of time, for sure.

**Comment by jaimejimbo** [comment]
Well, you have a point there.
