### ISSUE TITLE
F-Droid support?

### ISSUE THREAD

**Issue by jluttine** [federicoiosue/Omni-Notes#177]
I would love to see Omni Notes on F-Droid. Would it be possible to make the required changes to Omni Notes?

Some references on the topic:
https://github.com/federicoiosue/Omni-Notes/issues/20#issuecomment-105214738
https://f-droid.org/forums/topic/omni-notes/
https://f-droid.org/wiki/page/it.feio.android.omninotes

**Comment by federicoiosue** [comment]
It's not possible at the moment due toa couple of dependencies I use at compile time that are not open source (analytics and play services)

**Comment by Mosrite** [comment]
Are there plans to change this in the long run? What are Play Services used for?

**Comment by federicoiosue** [comment]
@Mosrite actually I'm not planning to make any changes on this side.

Due to the fact that ON has begun a quite complex application all my attempts to avoid a deep dependecy with Google's third party libraries are now slowing the development.

Play services are now used just for some internal checks but moving in their direction for what concerns geolocation and user authentication could be really make my life easier.

**Comment by federicoiosue** [comment]
@Mosrite the **newcoming 5.1 Beta will be released as FOSS**.

I'd like to move closed source dependencies to external apps to be plugged-in just under special cicrumstances.

**Comment by Mosrite** [comment]
That's awesome, thanks! Maybe we'll see ON on F-Droid after all?

**Comment by federicoiosue** [comment]
This will actually require some time due to the fact that I'll have to develop all the needed code and make it stable before I can move it to the master branch (that F-Droid's guys will use to compile the app and distribute on their portal/mobile app)

**Comment by jluttine** [comment]
Really great news! :) Thanks a lot!

**Comment by AnderRasoVazquez** [comment]
Thanks for considering F-droid! =D

**Comment by federicoiosue** [comment]
A new request to be distrituited through F-Droid has been posted (https://f-droid.org/forums/topic/omni-notes/#post-16907).
Let's wait for answer.

**Comment by r0bbie** [comment]
Any update on this? Just to add myself to the list, I'd love to see Omni-Notes on F-Droid!

**Comment by federicoiosue** [comment]
No way, until for now: https://f-droid.org/forums/topic/omni-notes/

Il giorno mar 3 mag 2016 alle ore 13:27 Robbie Cargill <
notifications@github.com> ha scritto:

**Comment by github-user-1** [comment]
Just wanted to throw in that I as well would really like to see ON on F-Droid. Keep on the good work and I keep my fingers crossed it will be possible with F-Droid at some point in time!

**Comment by r0bbie** [comment]
Likewise it seems a real shame there's currently still a blocker to Omni-Notes making it onto F-Droid.

Is the only blocking issue now the use of jitpack? I see jitpack referenced in other F-Droid pull requests (https://github.com/f-droid/fdroiddata/commit/367aa58bfd6170b18cd964f09818b4a653ae41e8) so perhaps this is now resolved?

**Comment by federicoiosue** [comment]
JitPack is a great tool directly connected to ON's source code on GitHub.
They simply perform a build like any Jenkins or similar CI tool does but on a rootless Docker container.

I've understood that the F-Droid policy is to retrieve and **locally** build any distribuited software's dependency (while for example on [TravicCI](https://travis-ci.org/federicoiosue/Omni-Notes) Omni Notes is built by using compiled dependencies).

I'll give a look asap at the link @r0bbie reported to get more informations.

**Comment by relan** [comment]
Omni-Notes 5.2.15 still includes a proprietary component: `com.google.android.gms:play-services-location` (required by `io.nlopez.smartlocation:library`). That's a show stopper for F-Droid.

**Comment by r0bbie** [comment]
@federicoiosue is there any reason for Omni-Notes including this at present?

**Comment by federicoiosue** [comment]
I've already prepared the script to build Omni Notes using the FDroid framework but I'm having some issues on my machine and few time at the moment to work on that. I'll eventually attach it here, maybe someone has a clean machine that will cause less issues.

For what concerns io.nlopez.smartlocation:library I'm using it because it's a nice wrapper around geolocation code with support for Observers (reactive java). 
Actually I'm using its open-source implementation (the same I used before into the app, manually crafted) but from what you're saying it includes closed source code at compile time.
I'll give a look to newer version to see if that's already been implemented, otherwise mi idea is to fork it and prepare a FOSS-compatible version of it.

**Comment by mimf** [comment]
Any news regarding this? I would like to see ON on fdroid.

**Comment by federicoiosue** [comment]
@mimf I've submitted on their new issue tracker: https://gitlab.com/fdroid/rfp/issues/16

**Comment by federicoiosue** [comment]
Omni Notes is now available on F-Droid

**Comment by CryptOwl** [comment]
Releases 5.5.3 and 5.5.4 are not available via F-Droid. Looks like those two version weren't detected as latest releases: https://f-droid.org/wiki/page/it.feio.android.omninotes.foss

**Comment by federicoiosue** [comment]
@CryptOwl It's due to #676 and #669
