### ISSUE TITLE
Bug: Omni Notes crashing when upgraded from 5.0.1 to 5.0.3

### ISSUE THREAD

**Issue by Immortalin** [federicoiosue/Omni-Notes#179]
Omni Notes crashes when upgraded from 5.0.1 to 5.0.3, logcat shows a resource not found exception.

**Comment by federicoiosue** [comment]
The log itself could be write useful here...

**Comment by federicoiosue** [comment]
Did you found the problem @Immortalin ?

**Comment by Immortalin** [comment]
No I have not. I am suspecting that my xprivacy configuration has something to do with it but it no longer matters as omninotes works perfectly well after I restored the data from the old version of the app into the new one.

**Comment by federicoiosue** [comment]
I'm asking because to reduce the app size I'm stripping out useless classes
and resources.

Due to the fact that some references to them are not hardcoded something
could be stripped wrongly.

If you encounter again similar problems please report the log so that I can
find out what I missed.

Il giorno ven 3 lug 2015 10:15 Immortalin <notifications@github.com> ha
scritto:

> No I have not. I am suspecting that my xprivacy configuration has
> something to do with it but it no longer matters as omninotes works
> perfectly well after I restored the data from the old version of the app
> into the new one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/federicoiosue/Omni-Notes/issues/179#issuecomment-118270910>
> .
>
-- 

Federico Iosue
