### ISSUE TITLE
Make reminders stay until archived

### ISSUE THREAD

**Issue by sb56637** [federicoiosue/Omni-Notes#189]
Hello,

Thanks a lot for developing Omni Notes. 

For my usage scenario, I don't always need a reminder, but I do need to specify a due date for some tasks. Additionally, sometimes I miss the due date, or the due date is flexible. For notes with reminders, it would be nice if the reminder would remain (or repeat) until I archive the note, thus marking it as finished.

Additionally, if it is a recurring reminder, I sometimes miss the reminder or dismiss it, but I haven't yet finished the task. So as mentioned above, could the reminder remain (or repeat) until I archive the note?. In the case of a recurring reminder, it would be good for it to not set the next reminder date until I archive it.

I think this might give extra value to the archive feature of Omni Notes and make it more flexible for those who use it to manage tasks with due dates.

Thanks again!

**Comment by federicoiosue** [comment]
Hi, thanks for your feedback.

Well I thinked about this too, but you have to think to ON like something different from a task manager like (just as an example because I use that) Trello, where tasks have a due date but then, if still uncomplished, they stay there saying "hey, you have to mark me as done"!

Here you have a notification that you have to do something and, like a calendar, it's up to you to decide if you want to move it foward changing its alarm, keep your notification there to remind you what to do in a few or simply dismiss and forget it.

One nice thing you can do is to add DashClock as a widget to your home screen and see there your early expiring notes.
