### ISSUE TITLE
Duplicate note (templates)

### ISSUE THREAD

**Issue by g36054** [federicoiosue/Omni-Notes#286]
Similar to #267. A simpler version would just be a duplicate note option. Then each could be edited as necessary.

**Comment by andr222** [comment]
Such a function would make it easier to split a note that became too long.

**Comment by federicoiosue** [comment]
Actually just sharing a note with ON itself reaches the same result as some kind of "duplicate" action.

This is my personal workflow:

1. Get a note to clone/duplicate/use as template
2. Share it with Omni Notes itself
3. A new separate note, with separate attachments will be created from the original one
4. Edit new note as desired (I usually remove unwanted informations because also for me this is mostly useful for information separation) and save it
