### ISSUE TITLE
AsyncTask.execute in DetailFragment

### ISSUE THREAD

**Issue by frankFic** [federicoiosue/Omni-Notes#395]
Hi,
I noticed you are using both AsyncTask.execute and AsyncTask.executeOnExecutor in [DetailFragment](https://github.com/federicoiosue/Omni-Notes/blob/a091ace09a0f83a40d769aeda65a1ab89f4cb24c/omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java). Why not all using executeOnExecutor to make the tasks run on real multi threads? Especially in handleEvents where multiple tasks could be started at the same time (like line [537](https://github.com/federicoiosue/Omni-Notes/blob/a091ace09a0f83a40d769aeda65a1ab89f4cb24c/omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java#L537)).

By the way, I also found that on [1575 still DetailFragment](https://github.com/federicoiosue/Omni-Notes/blob/a091ace09a0f83a40d769aeda65a1ab89f4cb24c/omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java#L1575), you checked the API level before calling executeOnExecutor. This is no more necessary as the minSDK is now 14.

Thx.

**Comment by federicoiosue** [comment]
Actually replaccing pretty much all the usages of AsyncTasks with rxJava would be a nice refactoring but most of that method calls wouldn't gain that much advantage (except the one you noticed).

This must be a realy old backward refactoring due to problems in automatic threads pool management that I'm sure are fixed now, so I could refactor all that calls to _executeOnExecutor_ once again.

I'll try, thanks for the feedback about it!

**Comment by federicoiosue** [comment]
> By the way, I also found that on 1575 still DetailFragment, you checked the API level before calling executeOnExecutor. This is no more necessary as the minSDK is now 14.

Raised to 16 and removed many checks like that all around the code.
