### ISSUE TITLE
Import from Noteeverything

### ISSUE THREAD

**Issue by dapgo** [federicoiosue/Omni-Notes#486]
It would be great to import from other Notes software, In fact I would like to move from Noteeverything to Omni Notes.
Noteeverything doesn't export to a file but it stores its data in a sqllite format file called .bgbackup which contains a table called Notes where subject, data and category is stored.

**Comment by federicoiosue** [comment]
Hi, this is a really specific task. 

Currently just importing data from Springpad works, it has been implememented when the service has been shutted down, but for other similar apps the best way is to **share** every single note from the source to Omni Notes.

**Comment by dapgo** [comment]
I´ll try to write the sql queries the move entries from noteeverything db to Omninotes db. 
Are you interested in the procedure to add this feature for other users?

**Comment by federicoiosue** [comment]
Something similar to this should be implemented to achieve that. I'm actually not that much interested into developing that, mainly because I've already a rich roadmap and a quite limited time so I'll mark this as Help wanted in case some other developers (maybe you yourself?) may take the task in charge

**Comment by dapgo** [comment]
Besides other information, in the following github project you have the sqlite scripts used to move notes from Noteeverything to Omni-Notes. [PIM_Data_Interoperability (github) ](https://dapgo.github.io/PIM_Data_Interoperability/)
