### ISSUE TITLE
Is it possible to create sublist in checklist?

### ISSUE THREAD

**Issue by vasili111** [federicoiosue/Omni-Notes#658]
Is it possible to create sublist in the checklist?
I mean like this:
https://i.imgur.com/4edeIZt.png

**Comment by azzamsa** [comment]
Hardly needed this feature too. Is this will be added?

**Comment by federicoiosue** [comment]
Hi, that's not on the roadmap for this app, sorry.

**Comment by azzamsa** [comment]
May we know the reason why? is it because hard to implement or something else?. Cause I think this feature is one of the main feature of most todo list app.

**Comment by federicoiosue** [comment]
Because the [library I'm using to implement checklists](https://github.com/federicoiosue/checklistview) would require a deep rewrite to allow that feature and newcoming changes for the app don't point on that direction currently.

Obviously, being both of that projects open-source, any contribution is welcome and if someone would ever implement that feature I'd be glad to include into OmniNotes!

**Comment by azzamsa** [comment]
Thanks, that what I suspect too. I will need the complete rewrite. Thanks lot for omni-notes.

For now maybe I will use someting like:

```
[] foo
[] - sub foo
[] -- sub sub foo
[] bar
```

To make me aware of the sublist.
