### ISSUE TITLE
Request for ongoing notification

### ISSUE THREAD

**Issue by alekksander** [federicoiosue/Omni-Notes#723]
Please add support for ongoing notification per note. This would be very handy for people like me, who want to be reminded of „to do” just by looking at the screen, without entering any application. Because Omni Notes lacks this feature I have to use two noting applications. One to keep more serious stuff, and another for daily „to do”which is constantly visible on top drawer. Thank You.

**Comment by alekksander** [comment]
@federicoiosue is there a chance to introduce it?

**Comment by federicoiosue** [comment]
Would you please provide a couple of screenshots to better understanding how should that work?

**Comment by alekksander** [comment]
![Screenshot_20191205-162511-2](https://user-images.githubusercontent.com/3148302/70249375-9a47c600-177c-11ea-9fb0-c36cdc53c463.png)

doesn't have to look like this (icons, button), the point is to have notification for preferred notes that can't by swiped away by accident.

**Comment by federicoiosue** [comment]
Ok, I've got it. 
Actually that seem to be just plain note reminder or maybe that app directly creates pinned notifications like that. I believe that the goal of that app is different than the one of Omni Notes so that behavior will not be implemented here, at least by me. 
But notifications' redraw is on the roadmap so they'll be improved a little, eventually by adding an option directly into the app to let the user choose if the must be pinned or not (globally).

**Comment by federicoiosue** [comment]
![](https://i.imgur.com/Lwpn8rT.jpg)

An example for future improvement. Maybe adding a third action

**Comment by alekksander** [comment]
looking forward for the improvements and will relate to them once it's released. thanks!

ps.
i think pinning notes is especially useful for checklists, where we can access app directly from notification of ongoing checklist.

**Comment by federicoiosue** [comment]
In the end I've done exactly as you recommended.
Currently pinned notes are not restored on device reboot, because that would require more work even on persistence and I believe this already should suit.

**Comment by alekksander** [comment]
Thank You.
