### ISSUE TITLE
Implementing Markdown in Notes

### ISSUE THREAD

**Issue by AdmiralOwl** [federicoiosue/Omni-Notes#735]
Hello!
Thanks for your work, really great piece of app right there.

Is there a chance to see a simple markdown (or text formating) system implemented any time soon?
This would improve the feasibility of the notes and improve the general look of them.

Examples: See Github edition bar - Bold, italic, underline, dot list, headers (?) etc... 

Implentation ideas:
- Selecting text and displaying a responsive tooltip with "B I U H1 H2" etc.
- Or markdown formatting (adding code in notes like **hello** for bold).

**Comment by federicoiosue** [comment]
Hi, thanks for your feedback. 

Actually, even if that's a really nice feature to have, it's not on ON's roadmap because that would require a quite big rewrite because the app has been focused on performances (is born to support legacy devices too) and what you're asking for has been ecluded "by design" since the early developments.

**Comment by Coehill** [comment]
Could a compromise here be the ability to export notes as Markdown?

**Comment by federicoiosue** [comment]
Would be pretty much the safe effort because there is no font styles at all in Omni Notes. 
I suppose you would benefit eventually of:

- Images 
- Checklists

But this would be a one-direction only process and I believe a special attention would have nneded to put into how this transformation would have to be done.

Given all the above I don't think I'll personally add it to the roadmap but, I mean, this is an open source project and would be great if this feature wold be added by anyone else!
