### ISSUE TITLE
Material Theme 

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#74]
Give a look to the great mockup by Manuel Sigle here  https://plus.google.com/102456677471445326610/posts/UATKgWieFUe

**Comment by Micks29** [comment]
Device: Samsung Galaxy S2
ROM: CyanogenMod 11 Kitkat 4.4.4
Omni Notes version: v5.0.0 b4

Hi, this app is awesome thanks for it!
I've noticed a few issues related with the new Material design:

1) The top of the pencil on the new (beautiful) icon app doesn't follow Material design, see pencil on this picture below for exemple: ![05ba17ac-5604-11e4-87ad-7d29a01dc62e](https://cloud.githubusercontent.com/assets/6850125/5611406/88157e8e-94c6-11e4-94f2-25f13d417528.png)
But maybe it's a design wanted?

2) Snackbars don't follow Material design too, see difference between the wrong & right display on the screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=818615Screenshot20150105094219.png"><img src="http://img4.hostingpics.net/thumbs/mini_818615Screenshot20150105094219.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=964137Screenshot20150105094816.png"><img src="http://img4.hostingpics.net/thumbs/mini_964137Screenshot20150105094816.png" alt="Upload images" /></a>
Can you implement [this library](https://github.com/nispok/snackbar) for see if it's better?

3) Navigation drawer is too big on my device it take almost all the screen and the status bar is not darker than the rest when it is open, see screenshot below:
<a href="http://www.hostingpics.net/viewer.php?id=881728Screenshot20150105094232.png"><img src="http://img4.hostingpics.net/thumbs/mini_881728Screenshot20150105094232.png" alt="Upload images" /></a>

Otherwise, why not implement a beautiful header for the navigation drawer with main color of the app, icon, name & version app?
See navigation drawer from Chronus for example in screenshot below:
<a href="http://www.hostingpics.net/viewer.php?id=694006Screenshot20150105094826.png"><img src="http://img4.hostingpics.net/thumbs/mini_694006Screenshot20150105094826.png" alt="Upload images" /></a>

4) Menu & dialog from the main screen have not the Material design, need to be improved for users with Menu hardware button, see screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=468620Screenshot20150105094326.png"><img src="http://img4.hostingpics.net/thumbs/mini_468620Screenshot20150105094326.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=620609Screenshot20150105094335.png"><img src="http://img4.hostingpics.net/thumbs/mini_620609Screenshot20150105094335.png" alt="Upload images" /></a>

5) In the password tab texts are cut no way to read it, see screenshot below:
<a href="http://www.hostingpics.net/viewer.php?id=322660Screenshot20150105094303.png"><img src="http://img4.hostingpics.net/thumbs/mini_322660Screenshot20150105094303.png" alt="Upload images" /></a>

Thanks in advance, 
Mickaël.

**Comment by federicoiosue** [comment]
Hi Mickaël, 

thanks for the accurate feedback, here my answers point by point:

1. That icons are meant to be used as action icons and perfectly reflect material design principles but **they have not to be used everywhere**.
In our particular situation, if you look at the current ON app's icon, you'll see that the top-left part of the pencil cuts the symbolic row really near to its starting point. Cutting the pencil to obtain the same result as the Google's action item icon would result in something similar to a mosaic, and the result will not be so pleasant for the eyes.

2. For what concerns the positioning what you see in ON is a desired design choice. This because I have to deal with a translucent navigation bar, so putting a snackbar on top of a transparent item will result in a total break with the "material" concept.
But I see that that I missed something with the internal items metrics, and I've got to modify them, thanks for letting me know.

3. The navigation drawer is actually **less** than the maximum size the specifications allow. For what concerns the statusbar color I'll check but it's not really a priority due to the fact that porting a **perfect** material layout to APIs <= 21 is not so easy because Appcompat v21 is still under development: some components are missing a some others are actually affected by some heavy bugs. On Lollipop statusbar has the right color.

If you give a look to the example you reported from Chronus' app you can easily see that no special effects are used in that case.

The navigation drawer header is actually just a placeholder: that will be the place where user's Google profile will appear once the sync feature will be ready.

4. I see. I effectively didn't tried with a device with physical soft-keys. I'll double check this behavior, thanks.

5. I'll check this too.

**Comment by Micks29** [comment]
Hi, 
Thanks for you quick reply!

1) Yes indeed you're right!

2)You're right again, sorry I've not navigation bar on my device.

3) Ok well I've this issue with others apps, it's maybe a dpi issue on my device but I don't know really.

4 & 5) Thanks!

**Comment by Micks29** [comment]
Hi Federico,
 
5) issue fixed on Beta 5.0, thanks!

Since my first report I've found others small issues.

6) When I use Android interface instead of Google for set a reminder, I've a black background for date popup it will be possible to have the same white background as clock popup? Screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=360093Screenshot20150113085205.png"><img src="http://img4.hostingpics.net/thumbs/mini_360093Screenshot20150113085205.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=983190Screenshot20150113085218.png"><img src="http://img4.hostingpics.net/thumbs/mini_983190Screenshot20150113085218.png" alt="Upload images" /></a>

7) In Info tab the action bar appears in stable version but not in beta version and icon is too big in beta, screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=229113Screenshot20150106140352.png"><img src="http://img4.hostingpics.net/thumbs/mini_229113Screenshot20150106140352.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=741579Screenshot20150113085244.png"><img src="http://img4.hostingpics.net/thumbs/mini_741579Screenshot20150113085244.png" alt="Upload images" /></a>

8) In settings when I go to in a tab it take the appropriate name in stable version but not in beta version, still with "Settings" name, screenshots below:
<a href="http://www.hostingpics.net/viewer.php?id=732905Screenshot20150106140526.png"><img src="http://img4.hostingpics.net/thumbs/mini_732905Screenshot20150106140526.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=589764Screenshot20150113085309.png"><img src="http://img4.hostingpics.net/thumbs/mini_589764Screenshot20150113085309.png" alt="Upload images" /></a>

**Comment by federicoiosue** [comment]
@arjerine , @Micks29 Just to see an "anti-design-pattern" in action (starting from the point of view that what's not perfectly accepted from guidelines in an anti-pattern: https://plus.google.com/102629628248642947234/posts/VHK89tVYEgX

**Comment by Micks29** [comment]
@federicoiosue, I've a "can't find this post" error when I click on your link.

**Comment by federicoiosue** [comment]
Strange, the link is correct, I can open it

**Comment by arjerine** [comment]
Same here. Couldn't open it.

**Comment by federicoiosue** [comment]
My fault: it's due to the fact that I haven't got your contacts in my G+ circles!

Anyway, was just a joke (even if true!)

![inbox-meme](https://cloud.githubusercontent.com/assets/487104/5828050/508c6a4a-a100-11e4-8203-f09c07c85abc.png)

**Comment by Micks29** [comment]
Hi @federicoiosue,

nice FAB on the second screen, with not implement same thing on your app like on Pushbullet does :p I know by a long press there are checklist and camera features but by short press we could have note, checklist and camera features, it would be great stuff!

Updated report after install beta 6:

4) issue almost fixed, now I've a white font on a white background, screenshot:
<a href="http://www.hostingpics.net/viewer.php?id=438024Screenshot20150121085019.png"><img src="http://img4.hostingpics.net/thumbs/mini_438024Screenshot20150121085019.png" alt="Upload images" /></a>
BTW "Sort by" would be better than "Sort" I think, no?

6), 7) & 8) Fixed!

9) Settings tab and sub tabs (Data, Interface, etc...) have not the same darker status bar than Info tab and main screens (Notes, Archive, etc...), screenshots:
<a href="http://www.hostingpics.net/viewer.php?id=849275Screenshot20150121085033.png"><img src="http://img4.hostingpics.net/thumbs/mini_849275Screenshot20150121085033.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=218034Screenshot20150121085045.png"><img src="http://img4.hostingpics.net/thumbs/mini_218034Screenshot20150121085045.png" alt="Upload images" /></a> <a href="http://www.hostingpics.net/viewer.php?id=347175Screenshot20150121085004.png"><img src="http://img4.hostingpics.net/thumbs/mini_347175Screenshot20150121085004.png" alt="Upload images" /></a>

10) When I go in a tab related with preferences and then go back Settings tab is renamed Preferences. I've not a problem like this when I go to in Info tab and then go back by example, screenshots:
<a href="http://www.hostingpics.net/viewer.php?id=479586Screenshot20150121085102.png"><img src="http://img4.hostingpics.net/thumbs/mini_479586Screenshot20150121085102.png" alt="Upload images" /></a>

Last thing, it's not a bug. I would like just have the translations updated for next beta for check my French translation related with latest strings added to the Crowdin project.

Thanks!

**Comment by federicoiosue** [comment]
Well I'd say that the migration has been completed.
