### ISSUE TITLE
Tag renaming

### ISSUE THREAD

**Issue by dvsdata** [federicoiosue/Omni-Notes#765]
Would it be possible to allow bulk renaming of tags?

Cheers,

**Comment by dvsdata** [comment]
Ok, I found a way of doing this by applying a new tag to a selection of notes. But, in so doing, I lost all the other tags on the selected notes...

**Comment by federicoiosue** [comment]
Hi there, I gave a look to the app's behavior.
What currently happens is the following:

1. You have more than one note with tags already existing associated
2. You bulk select them and use the option to associate tags
3. What you have here, differently than when you do the same thing from inside note editor, is that you don't have any pre-selected tag

So, the bulk notes tagging feature currently is something like "edit tags for selected notes starting from scratch". This could by not the better thing for your situation but it's ok if you want to have full control on tagging.

Another solution could be to preselect the union of the whole set of tags but this would also change the previously associated tags to any of the notes.

More, let's say that this works as an "add tag" feature, but what if I want to bulk remove?

**Comment by federicoiosue** [comment]
Otherwise (just a mockup to remind myself a possible approach)
<img width="38" src="https://user-images.githubusercontent.com/487104/84363050-730bfe80-abce-11ea-82f8-03eb6b7fc86a.png">

**Comment by dvsdata** [comment]
The three-state checkboxes would be awesome... Keep up the good work!

**Comment by federicoiosue** [comment]
Unlucky has not been possible to follow the three-state checkboxes way due to the fact that the library used for dialogs doesn't support that and injecting that behavior into third party dependency would have been difficult to maintain in future versions.

So now the behavior is changed as into the hypothesis stated above, that seems more intuitive: _...preselect the union of the whole set of tags but this would also change the previously associated tags to any of the notes..._
