### ISSUE TITLE
Please add auto cropping features and filter options when clicking image

### ISSUE THREAD

**Issue by Supriyo9** [federicoiosue/Omni-Notes#830]

**Comment by federicoiosue** [comment]
Hi there, thanks for the feedback but could you please elaborate a bit more?

**Comment by Supriyo9** [comment]
@federicoiosue I would like to suggest you that this note making app is amazing but few more features can make this more useful such as :-
1.this app having simple camera to add images to notes ,but as it is note app so it will be better  if this camera should have features of auto crop and filter options such as black and white , lighten, etc so that user can  modify or edit images before adding to notes as per their requirement.
2. And also now a days user prefer to share pdf ,docx document of their notes so it will be better if this feature also will be added.

Hope you will understand  my suggestion . Still if you need more explanation please feel free.

**Comment by federicoiosue** [comment]
Perfectly clear, thanks for the explanation but, for both, the answer is: not one of the goals of ON app.
Detailing a little bit more:

1. Image cropping and filtering is a so much specific tasks! Adding that feature would require to add quite big dependencies and/or working really hard to achieve surely a smaller result than the one achieved by specific apps that are created just to do that. So, this can be done by getting the picture from outside of ON, filtering/cropping as desired and then sharing to ON.
2. Here also implementing transformation to other formats is as much specific as useless, due to the fact that sharing a note to MS Office or Adobe to perform the transformation and then go with a second sharing step would have the same effect.

All of these is well described by [Single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle)
