### ISSUE TITLE
Backup import broken on F-Droid Version

### ISSUE THREAD

**Issue by Beliriel** [federicoiosue/Omni-Notes#846]
I just wanted to import a backup from my old phone which used the Google version which is on Changelog 6.0.5 to the newly installed Foss version from F-Droid which is on Changelog 5.5.2.
Understandably I'm unable to import a backup from 6.0.5 to 5.5.2 even with XML-renaming. Why is the F-Droid version on a lower major release number?

**Comment by federicoiosue** [comment]
The two versions are quite different by looking at underlying operations, so are not compatible just by replacing the app and renaming the XML because some paths are hardcoded into the package at build time, depending on the flavor (GooglePlay, FOSS, Alpha, Beta).

Moreover the new stable is being release theese days on Play Store so, my personal advice, is just to switch to that version.
