### ISSUE TITLE
Tracker in Omni Notes?

### ISSUE THREAD

**Issue by terry9873** [federicoiosue/Omni-Notes#859]
Hi, I am slowly tidying up my privacy on my phone. I have used OmniNotes for a good year or two, love it. 
I was advised by a friend to run ClassyShark3Xodus which scans all installed apps for trackers. I notice one for Omni Notes. Could someone explain please as I would assume that should be a concern, but I don't know enough about how it defines a 'tracker' to know if it's something I should be concerned about, or not. thanks

**Comment by federicoiosue** [comment]
Hi @terry9873,

I don't actually know how that application works nor the approach it uses to categorize as "tracker" a library, code, whatever.

I tried to use it to scan Omni Notes FOSS (the current version from F-Droid) and here is what I'm getting back:

![photo_2022-06-24 18 01 15](https://user-images.githubusercontent.com/487104/175573599-a35cb3a4-e0a0-44a6-9973-0d523d452fb2.jpeg)

Two external librares are categorized as trackers, and they are:
1. Piwik: an open source analytics tool ([link](https://matomo.org/))
2. ACRA: a crash tracker/repoter library ([link](https://github.com/ACRA/acra))

Differently, the latest release on Google Play Store seems to contain just one tracker: ACRA

![Screenshot_20220624-175719811](https://user-images.githubusercontent.com/487104/175573060-67f29570-e2b1-45db-9fc5-9eccc9698cbc.jpeg)
 
I've in fact removed Piwik from the last release. The reason? Nothing concerning privacy or whatever: aggregated and anonymous data don't affect privacy in any way, while they're really useful for end users because having informations on applications' usage is so much important for developers to decide what focus on and what leave back or remove.

ACRA will stay there forever: is the only way to get informations on issues and crashes without having to rely on Google itself, that is out of my (and yours, as end user) control.

I hope I gave you the answer you expected.
