### ISSUE TITLE
"Show App Tour Again" broken

### ISSUE THREAD

**Issue by PinkRay7** [federicoiosue/Omni-Notes#867]
### Step to repoduce
1. Open Settings.
2. Click "App tour".
3. Click "Confirm".
4. See nothing happens.

### Expected behavior
The application tour shows again.
This bug may be a regression one, the application tour shows normally on 5.5.4.
Video from 5.5.4:

https://user-images.githubusercontent.com/53887881/195014265-f8e7cd51-a778-4764-892e-a93250b3d517.mp4

### Actual behavior
Nothing happens.

https://user-images.githubusercontent.com/53887881/195014409-860c7f85-cce3-42ba-94a3-2c36566b306b.mp4

### Environment
Android version: 8.0
Device: Google Pixel 2
App Version: 6.1.0

**Comment by XYIheng** [comment]
I have encountered the same issue. There must be a functional failure in the "Show App Tour Again".

**Comment by tappdesign** [comment]
Could be probably fixed in `SettingsFragment.java`:

`  Prefs.edit().putBoolean(PREF_TOUR_COMPLETE, false).apply(); ` 

Instead of **.apply**, it should be to used **.commit**. (For synchronous calling).

This is very fast fix, but maybe it is not preffered, because `.commit` should be not called from UI thread

**Comment by federicoiosue** [comment]
Thanks for the feedback!
In the end I thought that there was no special reasons for having to restart the app just to show again the tour, so I decided just to explicitly launch it.
