### ISSUE TITLE
Feature request: save button

### ISSUE THREAD

**Issue by Chrizzle** [federicoiosue/Omni-Notes#877]
When a notes is finished, the button tot Dave and exit it could be a floating button on the bottom right corner, thats more convenient that the top left.

(Speaking for right handed users here)

Regards Chris

**Comment by federicoiosue** [comment]
This is not appliable due to UX guidelines: the icon is on top left, shown as an arrow because it cause a navigation trigger (goes back from detail to list of notes). Saving content is an implicit consequence of leaving the note detail without explicitly saying "undo changes", because keeping data it's safer than supposing the need to perform an explicit save action.

**Comment by Chrizzle** [comment]
Dear Federico,

I understand, my my explanation was not clear. What I meant is that 
'finishing' a note on the far top left is not ideal because you need to 
reach there with your finger, it is more logical to have it on the bottom 
right.
This button should have the same functionality as the current back-arrow 
(save and back to home). It could be a floating button, with the same 
function as the current button and  with even the same icon (arrow).
Attached BTW a screenshot of an app that has it like this and as far as I 
know complies with UX guidelines.


I do understand that my 'save'-button explanation was not the right 
description.


I hope this info helps,

Regards Chris






Op 8 november 2022 08:49:27 schreef Federico Iosue ***@***.***>:
