### ISSUE TITLE
Feature request: URL to hyperlink

### ISSUE THREAD

**Issue by Chrizzle** [federicoiosue/Omni-Notes#880]
It would be handy if URLs would be automatically converted to clickable  hyperlinks.

Regards Chris

**Comment by federicoiosue** [comment]
Hi Chris, they already are, unless you mean "converted in real time".
Or maybe some king of urls have not been converted even after note saved in your case?

**Comment by Chrizzle** [comment]
Dear Federico,

I see. I tested some more, in my situation:
- newly typed URLs are only converted, when the note is saved and reopened
- I did a test with a URL, but for some reason the URL in this specific case is not converted at all.


With this information the urgency is a bit lower. Although it would be preferred to have URL converted after pressing enter.

Regards Chris

**Comment by federicoiosue** [comment]
The first is actually a desired behavior, it makes easier to edit the current note and avoids performance drops (the app is aimed to work snappy also on older devices by design) for continuous text monitoring.

For what concerns the missed url recognition: would you be able to share the url, to double check the reason for the misbehavior?
