### ISSUE TITLE
Update targetSdkVersion to 30 or 31

### ISSUE THREAD

**Issue by jcperil** [federicoiosue/Omni-Notes#887]

**Comment by federicoiosue** [comment]
Done on latest Alpha release

**Comment by mecuricat** [comment]
Hey Federico, when will be update to api level 33?

**Comment by federicoiosue** [comment]
There is actually no specific pressure on this: the update to API 31 was necessary to publish new versions on Play Store.
Upgrading target API version is rarely a transparent process.

**Comment by federicoiosue** [comment]
Back to topic due to Android Developer's communication to update target SDK:

> Starting August 31, 2023:
New apps and app updates must target API level 33 to be submitted to Google Play (Wear OS must target API 30).Existing apps must target API level 31 or above to remain discoverable by all users on Google Play. Apps that target API level 30 or below (target API level 29 or below for Wear OS), will only be discoverable on devices running Android OS same or lower than your apps’ target API level.
You will be able to request an extension to November 1, 2023 if you need more time to update your app. You'll be able to access your app's extension forms in Play Console later this year.

So, yes, once the 6.2.0 version compatible with SDK31 will be released the work cycle to upgrade to SDK33 will begin.

Useful resource [here](https://developer.android.com/google/play/requirements/target-sdk).

**Comment by federicoiosue** [comment]
Since [version 6.3.0](https://github.com/federicoiosue/Omni-Notes/releases/tag/6.3.0) the app is targeting API 33
