### ISSUE TITLE
Backup location 

### ISSUE THREAD

**Issue by dbell154** [federicoiosue/Omni-Notes#892]
Where is the backup file located? It isn't documented any where.

**Comment by dbell154** [comment]
I'm using version Omni FOSS 6.10 from F-droid. What's the best way to get to 6.20 without losing existing data?

**Comment by dbell154** [comment]
Cancel that. I found the location of the FOSS version and imported into the Beta version. Not sure how I missed it. Thanks. 
Just wondering if I should stick with the beta version.

**Comment by federicoiosue** [comment]
Actually different versions are not 100% compatible (same applies to Alpha) due to different paths and package names, so if you go with one you should stay with that specific version.

Unlucky F-Droid doesn't provide itself a "beta" mechanism of apps' distribution so the release cycle is a little bit longer there.
