### ISSUE TITLE
Weblate for translations

### ISSUE THREAD

**Issue by comradekingu** [federicoiosue/Omni-Notes#902]
I use this, and wanted to contribute to the Translations.
Due to egregious terms, dual-licensing by contributing on Crowdin is less than ideal.
Crowdin is also a very quirky and broken tool, leading to drive-by translations.
The only translation with full coverage is nb_NO, and that could be a lot better.
The rest are almost all 6 months old.

I can help configure things for Hosted Weblate if you set up shop there and add "kingu", or on a self-hosted instance.
https://hosted.weblate.org/hosting/ is what most other similar projects use. :)

**Comment by federicoiosue** [comment]
The Weblate project seems very nice and attractive to me (having a complete FOSS stack would be wonderful) but currently Crowdin does it's job in terms of the simple tasks it's required to do.

Releases are rarely intensive for translations, due to the contributive nature of the translations themselves I always try to limit changes to texts, moreover most of the missing translations are related to Google Play Store contents, and to be honest I had to check to confirm that at least italian Play Store content is translated...

Given all of this I'd stay on Crowdin for now, but I've added a note about this opportunity into my personal backlog.
