### ISSUE TITLE
uriPath may be invalid on Android 10

### ISSUE THREAD

**Issue by TPKato** [federicoiosue/Omni-Notes#908]
OS: Android 10 (Nokia 6.1)

I updated Omni Notes to 6.2.3 today (maybe from 6.1.0) and noticed that some (but not all) photos are not displayed with the message "Attachment is not found" when I tap the thumbnail of the photos.
When I write a new note with photos, the photos are also not displayed.
The thumbnails for all photos are displayed correctly.

When I force rewrite json files from `content://it.feio.android.omninotes.authority/external_files` to `file:///storage/emulated/0` they work as expected.

The backup also fails, probably for the same reason (image files are created, but some files are empty).

**Comment by TPKato** [comment]
I have confirmed that the problem of some photos not being displayed has been fixed in 6.2.4 (thanks!).

But the backup still fails.
The files listed as `content://it.feio.android.omninotes.authority/external_files/...` in the json files (created by the old versions of Omni Notes) are created, but empty.

**Comment by federicoiosue** [comment]
That's true, there is still something to work on for what concerns backups, but this should not affect newly taken notes at least: if you perform a backup of a note created since version 6.2.4 that will have a working attachment.

As workaround you can share any note containing broken attachment with ON itself: this should create a new fixed note (then you can remove the older one).

**Comment by federicoiosue** [comment]
Closing as re-performing all database update procedures after a backup restore could bring to distructive results.
The correct restore procedure is to restore backups on the same app's version and just afdter this move on with app's upgrade.
