### ISSUE TITLE
Unable to add "add note" widget

### ISSUE THREAD

**Issue by BitFis** [federicoiosue/Omni-Notes#962]
Hello

I am unable to add the "add note" widget to my home screen.
I can select it and drag it, but the widget screen blinks
And the widget disapears from the home screen.
![Screenshot_20240114-135239](https://github.com/federicoiosue/Omni-Notes/assets/1985215/c1a9b7ad-2386-46a5-aa40-4f33f299d8f2)

App version: 6.3.1

My android version:
13
4.19.157-perf+
#1 Wed Nov 22 21:47:16 CST 2023
FP4.TP20.C.087.20231122

Thank you ❤️

**Comment by federicoiosue** [comment]
Hi Lucien, may it be an issue depending on the specific home launcher, because on Nova Launcher (Android 13) it seems to work fine.
I'll double check, thanks for reporting! 

Meanwhile you could replace that shortcut widget with the newer app's shortcut that should appear to you by long-tapping on the app icon and then dragging the shortcut into the launcher.

**Comment by BitFis** [comment]
Thank you, the newer version by long tabbing works fine. It might be the launcher. Tell me if i should test something specific.

**Comment by federicoiosue** [comment]
Closing as no other issue has been reported about this nor my attempts brang to somethung relevant.
